(() => {
const DB_NAME='SerieA9000_DB', DB_VERSION=1, CAREERS='careers', BACKUPS='career_backups', SETTINGS='settings';
let dbPromise=null;
function dbOpen(){if(dbPromise)return dbPromise;return dbPromise=new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(CAREERS))db.createObjectStore(CAREERS,{keyPath:'careerId'});if(!db.objectStoreNames.contains(BACKUPS)){const s=db.createObjectStore(BACKUPS,{keyPath:'backupId'});s.createIndex('careerId','careerId');}if(!db.objectStoreNames.contains(SETTINGS))db.createObjectStore(SETTINGS,{keyPath:'key'});};r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();dbPromise=null};res(r.result)};r.onerror=()=>{dbPromise=null;rej(r.error)};});}
const txDone=t=>new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error)});
const uuid=()=>crypto.randomUUID?crypto.randomUUID():'career_'+Date.now()+'_'+Math.random().toString(36).slice(2);
async function listCareers(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction(CAREERS).objectStore(CAREERS).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))));r.onerror=()=>rej(r.error)});}
async function putCareer(data,meta={}){if(!data||window.S9V10?.matchContext||window.S9V10?.standalone)return;const id=meta.careerId||data.careerId||uuid();data.careerId=id;data=JSON.parse(JSON.stringify(data));const db=await dbOpen();const now=new Date().toISOString();const old=await getCareer(id);const rec={careerId:id,careerName:meta.careerName||old?.careerName||`${data.manager||'Manager'} · ${data.user||'Carriera'}`,managerName:data.manager||'',clubId:data.user||'',seasonYear:data.seasonYear||1998,matchday:data.round||0,saveVersion:1,gameVersion:'V10 FINAL',databaseVersion:'V10',saveData:data,createdAt:old?.createdAt||now,updatedAt:now};const t=db.transaction(CAREERS,'readwrite');t.objectStore(CAREERS).put(rec);await txDone(t);return rec;}
async function getCareer(id){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction(CAREERS).objectStore(CAREERS).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});}
async function deleteCareer(id){const db=await dbOpen();const t=db.transaction(CAREERS,'readwrite');t.objectStore(CAREERS).delete(id);await txDone(t);}
async function backupCareer(data){if(!data?.careerId||window.S9V10?.matchContext||window.S9V10?.standalone)return;data=JSON.parse(JSON.stringify(data));const db=await dbOpen();const backupId=`${data.careerId}_${Date.now()}`;const t=db.transaction(BACKUPS,'readwrite');t.objectStore(BACKUPS).put({backupId,careerId:data.careerId,createdAt:new Date().toISOString(),saveData:JSON.parse(JSON.stringify(data))});await txDone(t);const all=await new Promise((res,rej)=>{const r=db.transaction(BACKUPS).objectStore(BACKUPS).index('careerId').getAll(IDBKeyRange.only(data.careerId));r.onsuccess=()=>res(r.result.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))));r.onerror=()=>rej(r.error)});for(const old of all.slice(3)){const tt=db.transaction(BACKUPS,'readwrite');tt.objectStore(BACKUPS).delete(old.backupId);await txDone(tt);}}
async function exportCareer(id){const rec=await getCareer(id);if(!rec)throw new Error('Carriera non trovata');const blob=new Blob([JSON.stringify({format:'SerieA9000Save',version:1,record:rec},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`SerieA9000_${(rec.managerName||'Manager').replace(/\W+/g,'_')}_${(rec.clubId||'career')}.s9save`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function importCareer(file){const raw=JSON.parse(await file.text());if(raw?.format!=='SerieA9000Save'||!raw.record?.saveData||!raw.record.saveData.user||!Array.isArray(raw.record.saveData.fixtures)||!raw.record.saveData.teamStates)throw new Error('Formato non valido');const rec=raw.record;rec.careerId=rec.careerId||uuid();const exists=await getCareer(rec.careerId);if(exists)rec.careerId=uuid();rec.saveData.careerId=rec.careerId;rec.createdAt=new Date().toISOString();rec.updatedAt=rec.createdAt;const db=await dbOpen();const t=db.transaction(CAREERS,'readwrite');t.objectStore(CAREERS).put(rec);await txDone(t);return rec;}
window.S9Save={listCareers,putCareer,getCareer,deleteCareer,backupCareer,exportCareer,importCareer,uuid};
})();