#!/usr/bin/env node
/* Offline developer checks. No dependencies and no changes to game/storage. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');process.chdir(root);
let checks=0;const ok=(condition,label)=>{assert.ok(condition,label);checks++};
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.name==='.git'||e.name==='node_modules'?[]:e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const files=walk('.'),html=fs.readFileSync('index.html','utf8');
for(const f of files.filter(f=>f.endsWith('.js')&&!f.endsWith('vite.config.js'))){new vm.Script(fs.readFileSync(f,'utf8'),{filename:f});checks++}
const inline=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)];
inline.filter(m=>!m[1].includes('src=')).forEach((m,i)=>{new vm.Script(m[2],{filename:`index:inline${i}`});checks++});
const markup=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/g,'');
const ids=[...markup.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);ok(ids.length===new Set(ids).size,'duplicate HTML IDs');
ok(/<!doctype html>/i.test(html)&&/<html[\s>]/.test(html)&&/<\/html>/.test(html),'HTML document structure');
const sources=[...html.matchAll(/<(?:script|link)\b[^>]*(?:src|href)=["']([^"']+)["']/g)].map(m=>m[1].split('?')[0]);ok(new Set(sources).size===sources.length,'duplicate script/style loading');
const dirs=new Map();function exactFile(f){const parts=path.relative(root,path.resolve(f)).split(path.sep);let dir=root;for(const part of parts){if(!dirs.has(dir))dirs.set(dir,fs.readdirSync(dir));if(!dirs.get(dir).includes(part))return false;dir=path.join(dir,part)}return fs.statSync(dir).isFile()}
const missing=[];
for(const f of files.filter(f=>/\.(html|css|js|json)$/.test(f)&&!f.startsWith('react-ui/')&&!f.startsWith('tools/'))){
 const text=fs.readFileSync(f,'utf8');
 ok(!/data:image\/[^;,]+;base64,[A-Za-z0-9+/=]{4096}/.test(text),`${f}: large embedded raster`);
 const refs=[...text.matchAll(/(?:["'`(])((?:\.\.\/)?assets\/[^"'`\s)<>]+\.(?:png|jpe?g|svg|webp))/g)].map(m=>m[1]);
 if(f==='index.html')refs.push(...sources);
 for(let ref of refs){if(/[${}]/.test(ref))continue;ref=ref.split('?')[0];const resolved=ref.startsWith('../')?path.resolve(path.dirname(f),ref):path.resolve(ref);if(!fs.existsSync(resolved)||!exactFile(resolved))missing.push(`${f}: ${ref}`)}
}
ok(missing.length===0,`Missing literal paths:\n${missing.join('\n')}`);
const nodes=new Map();function node(selector=''){if(nodes.has(selector))return nodes.get(selector);const n={value:selector==='#managerTeam'?'inter_9798':'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:{add(){},remove(){},toggle(){},contains(){return false}},children:[],options:[],innerHTML:'',textContent:'',addEventListener(){},removeEventListener(){},appendChild(){},prepend(){},insertAdjacentHTML(){},insertAdjacentElement(){},insertBefore(){},setAttribute(){},getAttribute(){return null},removeAttribute(){},querySelector:s=>node(selector+' '+s),querySelectorAll:()=>[],getBoundingClientRect:()=>({width:1280,height:720}),click(){},closest(){return null}};nodes.set(selector,n);return n}
const ctx={console,Math,Date,Intl,JSON,Set,Map,Array,Object,Number,String,Promise,Uint8Array,structuredClone,crypto:require('node:crypto').webcrypto,URL,Blob,setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:()=>0,addEventListener(){},innerWidth:1280,innerHeight:720,navigator:{userAgent:'audit',platform:'',maxTouchPoints:0},getComputedStyle:()=>({display:'block'}),MutationObserver:class{observe(){}},Image:class{},alert(){},confirm:()=>false,sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},localStorage:{values:new Map(),getItem(k){return this.values.get(k)||null},setItem(k,v){this.values.set(k,v)},removeItem(k){this.values.delete(k)}}};
ctx.window=ctx;ctx.scrollTo=()=>{};ctx.document={readyState:'loading',querySelector:node,querySelectorAll:()=>[],getElementById:node,createElement:node,documentElement:node('html'),body:node('body'),addEventListener(){}};
vm.createContext(ctx);const run=s=>vm.runInContext(s,ctx,{timeout:20000});
for(const m of inline){const src=m[1].match(/src="([^"?]+)/);let code=src?fs.readFileSync(src[1],'utf8'):m[2];if(src?.[1]==='js/v10-release.js')code=code.replace('function init(){injectScreens();',`V10.audit={FORMATS,createTournament,standaloneParticipants,processTournamentResult,nextUserTournamentMatch,simulateTournamentToEnd,resolveSingle,resolveTwoLeg,initCareerCups,normalizeTournament,createCareerV10,startFinalEight,advanceCareerSeasonV10,installOverrides,beginStandalone,continueStandalone,saveStandaloneState,leaveStandalone,syncCupCalendar,cupSlot,playTournamentFixture};\nfunction init(){injectScreens();`);if(src?.[1]==='js/v10-release.js')code=code.replace('function bootV103(){', 'S9.auditCondition={ensurePlayerState,teamTrack,processSilentEvents,finalizeMatchCondition,liveFitness};\nfunction bootV103(){');run(code)}
const data=run('({italian:S9V10.italianIds.map(T),foreign:V10_FOREIGN_TEAMS,national:V10_NATIONAL_TEAMS})');
const playerIds=new Set();for(const [kind,ts]of Object.entries(data)){
 ok(ts.length===(kind==='national'?61:32),`${kind} count`);ok(new Set(ts.map(t=>t.id)).size===ts.length,`${kind} unique IDs`);
 for(const t of ts){ok(!!t.name&&Number.isFinite(t.strength)&&t.strength>0&&t.strength<=100,`${t.id} metadata`);ok(t.players.some(p=>p.pos==='GK'),`${t.id} goalkeeper`);ok(t.formations.every(f=>f.split('-').reduce((a,b)=>a+Number(b),0)===10),`${t.id} formations`);
 for(const p of t.players){ok(!playerIds.has(p.id)&&!!p.name&&Number.isFinite(p.overall)&&p.overall>0&&p.overall<=100,`${p.id} player`);ok(Object.values(p.stats||{}).every(n=>Number.isFinite(n)&&n>=0&&n<=100),`${p.id} attribute bounds`);playerIds.add(p.id)}
 if(kind==='national')ok(t.id.endsWith('_'+t.season),`${t.id} year`);
 for(const asset of [`assets/crests/${kind}/${t.id}.png`,...['home','away'].map(k=>`assets/kits/${kind}/${k}/${t.id}.png`)])ok(fs.existsSync(asset)&&exactFile(asset),asset);
 }
}
run(`
var A=S9V10.audit;
var user=S9V10.italianIds[0];document.querySelector('#managerTeam').value=user;A.createCareerV10();A.installOverrides();
`);
function test(code,label){ok(run(code),label)}
test(`(()=>{selectedTeamIndex=0;renderTeamPicker();const id=S9V10.italianIds[0];return document.querySelector('#teamHomeKit').src===kitPath(id,'home')&&document.querySelector('#teamAwayKit').src===kitPath(id,'away')&&document.querySelector('#teamRightInfo').innerHTML.includes('OVR')})()`,'career picker has home/away kits and OVR');
ok(html.includes('class="s9-picker-kits"')&&fs.readFileSync('js/v10-release.js','utf8').includes('class="s9-picker-kits"'),'shared Career/Cup picker structure');
// A background class must never change the season content box's geometry.
const seasonVariantRules=fs.readdirSync('css').flatMap(f=>[...fs.readFileSync(path.join('css',f),'utf8').matchAll(/([^{}]+)\{([^{}]*)\}/g)]).filter(m=>m[1].includes('#seasonContent')&&/v51-(calendar|europe)-bg/.test(m[1]));
ok(seasonVariantRules.every(m=>!/(?:left|right|top|bottom|width|height|transform)\s*:/.test(m[2])),'Cup/calendar backgrounds cannot move the season content panel');
test(`(()=>{const el=document.querySelector('#season'),classes=new Set();el.classList={add:c=>classes.add(c),remove:c=>classes.delete(c),contains:c=>classes.has(c),toggle:(c,on)=>on?classes.add(c):classes.delete(c)};for(const view of ['europe','next','calendar','table','europe','results']){renderSeasonView(view);if(el.dataset.seasonView!==view||classes.has('v51-europe-bg')!==(view==='europe')||classes.has('v51-calendar-bg')!==(view==='calendar'))return false;}return true})()`,'Coppe / next / calendar / standings / results navigation resets background state');
test(`(()=>{const all=[...career.groups.A,...career.groups.B];return all.length===32&&new Set(all).size===32&&[career.fixtures,career.otherFixtures].every(f=>f.length===30&&new Set(f.flat().map(p=>p.join('/'))).size===240&&f.every(r=>new Set(r.flat()).size===16))})()`,'32 clubs, 16+16, 480 unique home/away fixtures');
test(`(()=>{for(let round=0;round<30;round++){career.round=round;for(const f of [career.fixtures,career.otherFixtures])for(const [h,a] of f[round]){const m={h,a,scoreH:2,scoreA:1};updateLeague(m);updateLeague(m)}}career.round=30;return S9V10.italianIds.every(id=>{const s=career.stats[id];return s.p===30&&s.w===15&&s.l===15&&s.d===0&&s.gf===45&&s.ga===45&&s.pts===45})})()`,'full regular season standings and duplicate-registration guard');
for(const key of ['italia','cdc','uefa','world','euro'])test(`(()=>{for(let i=0;i<20;i++){const u=${JSON.stringify(key)}==='world'?V10_NATIONAL_TEAMS[i].id:${JSON.stringify(key)}==='euro'?V10_NATIONAL_TEAMS.filter(t=>t.confed==='UEFA')[i%20].id:user;const ids=A.standaloneParticipants('${key}',u);const s=A.createTournament('${key}',ids,u);if(new Set(ids).size!==A.FORMATS['${key}'].participants)return false;if(s.groups&&s.groups.length!==A.FORMATS['${key}'].groups)return false;A.simulateTournamentToEnd(s);if(!s.completed||!ids.includes(s.champion))return false;for(const ties of Object.values(s.roundHistory))if(new Set(ties.flatMap(t=>[t.a,t.b])).size!==ties.length*2)return false;}return true})()`,`${key}: 20 complete tournaments`);
test(`(()=>{Object.values(career.v10Cups).forEach(A.simulateTournamentToEnd);A.startFinalEight();const s=career.v10FinalEight;const aa=v4Standings('A').slice(0,4).map(x=>x.t.id),bb=v4Standings('B').slice(0,4).map(x=>x.t.id);if(JSON.stringify(s.roundHistory.QF.map(t=>[t.a,t.b]))!==JSON.stringify([[aa[0],bb[3]],[aa[1],bb[2]],[bb[0],aa[3]],[bb[1],aa[2]]]))return false;A.simulateTournamentToEnd(s);if(s.ranking.length!==8||new Set(s.ranking).size!==8)return false;A.advanceCareerSeasonV10();return ['A','B'].every(g=>career.groups[g].length===16&&career.qualified.cdc.filter(x=>career.groups[g].includes(x)).length===2&&career.qualified.uefa.filter(x=>career.groups[g].includes(x)).length===2)})()`,'Final Eight seeds, ranking 1–8 and next-season redistribution');
test(`(()=>{const copy=S9V10.normalizeCareer(JSON.parse(JSON.stringify(career)));return copy.leagueDates.every(d=>d instanceof Date)&&copy.calendar.every(e=>e.date instanceof Date)&&JSON.stringify(copy.stats)===JSON.stringify(career.stats)})()`,'save serialization and date hydration');
test(`(()=>{const s=A.createTournament('italia',S9V10.italianIds,user),copy=A.normalizeTournament(JSON.parse(JSON.stringify(s)));return copy.roundHistory[copy.phase]===copy.ties})()`,'saved knockout bracket and active ties share state');
test(`(()=>{const st=career.teamStates[user];current=buildMatch(user,S9V10.italianIds[1]);const out=st.lineup[1],inp=st.players.find(p=>!st.lineup.includes(p.id));if(!S9V10.canSubstitute(st,out,inp.id))return false;S9V10.recordSubstitution(user,out,inp.id,45);st.lineup[1]=inp.id;st.subs++;if(S9V10.canSubstitute(st,inp.id,out))return false;const other=st.players.find(p=>!st.lineup.includes(p.id)&&p.id!==out);other.injuryGames=2;if(S9V10.canSubstitute(st,inp.id,other.id))return false;other.injuryGames=0;other.suspensionGames=1;if(S9V10.canSubstitute(st,inp.id,other.id))return false;other.suspensionGames=0;st.subs=3;return !S9V10.canSubstitute(st,inp.id,other.id)})()`,'substitution limit, no return, injury and suspension exclusions');
test(`(()=>{const c=S9V10.auditCondition,p={fitness:NaN,injuryGames:-4,suspensionGames:Infinity,yellowStreak:-2};c.ensurePlayerState(p);return p.fitness===100&&p.injuryGames===0&&p.suspensionGames===0&&p.yellowStreak===0})()`,'older/invalid condition defaults');
test(`(()=>{const C=S9V10.auditCondition,id=user,other=S9V10.italianIds[1];career.teamStates[id]=initTeamState(T(id));career.teamStates[other]=initTeamState(T(other));const st=career.teamStates[id],pid=st.lineup[1],p=st.players.find(p=>p.id===pid);for(let i=0;i<3;i++){const m=buildMatch(id,other);m.events=[{type:'yellow',side:'home',player:p,min:20}];C.processSilentEvents(m);C.finalizeMatchCondition(m,false);if(i===1&&p.yellowStreak!==2)return false}if(p.suspensionGames!==1||p.yellowStreak!==0)return false;const next=buildMatch(id,other);if(st.lineup.includes(pid))return false;next.events=[];C.finalizeMatchCondition(next,false);return p.suspensionGames===0&&p.fitness<=100&&p.fitness>=25})()`,'three consecutive yellows, diffida, one-match suspension, recovery');
test(`(()=>{const C=S9V10.auditCondition,id=user,other=S9V10.italianIds[1];const m=buildMatch(id,other),p=career.teamStates[id].players.find(p=>p.id===career.teamStates[id].lineup[1]);m.events=[{type:'yellow',side:'home',player:p,min:20},{type:'yellow',side:'home',player:p,min:50}];C.processSilentEvents(m);C.finalizeMatchCondition(m,false);const fitness=p.fitness;C.finalizeMatchCondition(m,false);return m._v103.teams[id].reds[p.id]&&m._v103.teams[id].exitedAt[p.id]===50&&p.suspensionGames===1&&p.fitness===fitness})()`,'second-yellow dismissal and idempotent physical finalization');
test(`(()=>{const C=S9V10.auditCondition,id=user,other=S9V10.italianIds[1];const m=buildMatch(id,other),p=career.teamStates[id].players.find(p=>p.id===career.teamStates[id].lineup[1]);m.events=[{type:'injury',side:'home',player:p,min:40,recovery:2}];C.processSilentEvents(m);C.finalizeMatchCondition(m,false);if(p.injuryGames!==2)return false;for(let i=0;i<2;i++){const n=buildMatch(id,other);if(career.teamStates[id].lineup.includes(p.id))return false;n.events=[];C.finalizeMatchCondition(n,false)}return p.injuryGames===0})()`,'injury duration excludes injury match and expires after two subsequent matches');
test(`(()=>{const s=A.createTournament('cdc',A.standaloneParticipants('cdc',user),user),m=A.nextUserTournamentMatch(s);const r={h:m.h,a:m.a,hg:1,ag:0};A.processTournamentResult(s,m,r);const count=s.results.length,index=s.groupMatchIndex;A.processTournamentResult(s,m,r);return s.results.length===count&&s.groupMatchIndex===index})()`,'group result registered only once');
test(`(()=>{const t={a:user,b:S9V10.italianIds[1],legs:[{h:user,a:S9V10.italianIds[1],hg:1,ag:0},{h:S9V10.italianIds[1],a:user,hg:2,ag:1}]};A.resolveTwoLeg(t,true);return t.winner===user&&t.note==='GOL IN TRASFERTA'})()`,'European away goals before extra time');
test(`(()=>{const t={a:user,b:S9V10.italianIds[1]};A.resolveSingle(t,{h:t.a,a:t.b,hg:0,ag:0},true);return t.note.startsWith('RIGORI')&&t.legs[0].hg===0&&t.legs[0].ag===0})()`,'Coppa Italia early rounds: direct penalties');
test(`(()=>{for(const key of ['italia','cdc','uefa','world','euro']){const u=['world','euro'].includes(key)?'italy_2006':user;let s=A.createTournament(key,A.standaloneParticipants(key,u),u);let guard=0;while(!s.completed&&guard++<20){s=A.normalizeTournament(JSON.parse(JSON.stringify(s)));const m=A.nextUserTournamentMatch(s);if(!m)return false;A.processTournamentResult(s,m,{h:m.h,a:m.a,hg:m.h===u?6:0,ag:m.a===u?6:0});}if(s.champion!==u)return false;for(const ties of Object.values(s.roundHistory))if(ties.some(t=>!t.winner))return false;}return true})()`,'played progression and reload between every leg for all five cups');
test(`(()=>{A.createCareerV10();career.round=2;const due=S9V10.dueCareerCup();A.syncCupCalendar(career);const dated=career.calendar.filter(e=>e.label.includes('COPPA ITALIA'));return due?.key==='italia'&&dated.length===6&&dated.every(e=>e.date.getDay()===3)&&new Set(dated.map(e=>+e.date)).size===6})()`,'career cup due before next league round, six distinct Wednesday slots');
test(`(()=>{const original=career;S9V10.selectedCompetition='world';S9V10.pickerPool=['italy_2006'];S9V10.pickerIndex=0;A.beginStandalone();const p=career.teamStates['italy_2006'].players[0];p.fitness=57;p.injuryGames=2;p.suspensionGames=1;p.yellowStreak=2;A.saveStandaloneState();A.leaveStandalone();if(career!==original)return false;A.continueStandalone();const loaded=career.teamStates['italy_2006'].players[0];const valid=loaded.fitness===57&&loaded.injuryGames===2&&loaded.suspensionGames===1&&loaded.yellowStreak===2;A.leaveStandalone();return valid&&career===original})()`,'standalone save restores fatigue/injury/cards and preserves career identity');
(async()=>{
 const result=await run(`(async()=>{A.createCareerV10();const initial=career.round;current={fixture:nextUserGame()};wait=async()=>{};ov=async()=>{};animAttack=async()=>{};setupPitch=()=>{};updateScore=()=>{};log=()=>{};crowd=()=>{};whistle=()=>{};goalRoar=()=>{};showPitchImportant=()=>{};hidePitch=()=>{};show=id=>{if(id==='halftime')Promise.resolve().then(()=>{const r=halfResolver;halfResolver=null;r()});if(id==='postmatch')S9V10.auditCondition.finalizeMatchCondition(current,false)};const first=launchMatch();await launchMatch();await first;return career.round===initial+1&&career.results.length===16&&current._finished&&current._v103.finalized})()`);
 ok(result,'played match lifecycle, halftime, finalization, duplicate-start guard');
 ok(await run(`(async()=>{A.createCareerV10();career.round=2;const savedFixtures=career.fixtures,savedStats=career.stats,savedResults=career.results;const state=career.v10Cups.italia,match=A.nextUserTournamentMatch(state);const originalPrematch=openPrematch;openPrematch=g=>{current={fixture:g}};A.playTournamentFixture(state,match,'careerCup');openPrematch=originalPrematch;await launchMatch();if(career.results.length!==0||!current._finished)return false;document.querySelector('#returnSeason').onclick();return career.round===2&&career.fixtures===savedFixtures&&career.stats===savedStats&&career.results===savedResults&&state.played===1&&S9V10.matchContext===null})()`),'played career cup restores league/calendar state without recording a league result');
 ok(await run(`(async()=>{const random=Math.random;Math.random=()=>.1;try{const h=user,a=S9V10.italianIds[1];for(const direct of [true,false]){const tie={a:h,b:a,twoLeg:false,directPens:direct};current={h,a,scoreH:0,scoreA:0,minute:90,keyEvents:[]};S9V10.matchContext={match:{kind:'knockout',tie,leg:1}};await S9V10.finishPlayedTie();const result=current.decider;if(!result||!result.note.startsWith(direct?'RIGORI':'GOLDEN GOAL'))return false;if(!direct&&current.scoreH!==1)return false;A.resolveSingle(tie,{h,a,hg:current.scoreH,ag:current.scoreA,decider:result},direct);if(tie.winner!==result.winner)return false;}return true}finally{Math.random=random;S9V10.matchContext=null;current=null}})()`),'played direct penalties / Golden Goal score and resolver preserve the same winner');
 // Model IndexedDB's asynchronous requests/transaction completion without touching user saves.
 const stores=new Map(),keys=new Map();let opened=false;
 const database={objectStoreNames:{contains:n=>stores.has(n)},createObjectStore(n,opts){stores.set(n,new Map());keys.set(n,opts.keyPath);return {createIndex(){}}},transaction(n){const tx={};tx.objectStore=()=>{
  const request=fn=>{const r={};queueMicrotask(()=>{try{r.result=fn();r.onsuccess?.();queueMicrotask(()=>tx.oncomplete?.())}catch(e){r.error=e;r.onerror?.();tx.onerror?.()}});return r};
  return {get:id=>request(()=>structuredClone(stores.get(n).get(id))),getAll:()=>request(()=>[...stores.get(n).values()].map(x=>structuredClone(x))),put:record=>request(()=>stores.get(n).set(record[keys.get(n)],structuredClone(record))),delete:id=>request(()=>stores.get(n).delete(id)),index:()=>({getAll:id=>request(()=>[...stores.get(n).values()].filter(x=>x.careerId===id).map(x=>structuredClone(x)))})};};return tx;}};
 ctx.indexedDB={open(){const r={result:database};queueMicrotask(()=>{if(!opened){opened=true;r.onupgradeneeded?.()}r.onsuccess?.()});return r}};ctx.IDBKeyRange={only:x=>x};
 ok(await run(`(async()=>{A.createCareerV10();career.manager='First';const saving=S9Save.putCareer(career);career.manager='Changed after snapshot';const first=await saving;if(first.saveData.manager!=='First')return false;A.createCareerV10();career.manager='Second';const second=await S9Save.putCareer(career);if(first.careerId===second.careerId||(await S9Save.listCareers()).length!==2)return false;const imported=await S9Save.importCareer({text:async()=>JSON.stringify({format:'SerieA9000Save',record:first})});if(imported.careerId===first.careerId||(await S9Save.listCareers()).length!==3)return false;S9V10.matchContext={};const blocked=await S9Save.putCareer(career);S9V10.matchContext=null;if(blocked!==undefined)return false;let rejected=false;try{await S9Save.importCareer({text:async()=>'{bad'})}catch(e){rejected=true}return rejected&&(await S9Save.getCareer(first.careerId)).saveData.manager==='First'})()`),'save API: immutable snapshots, independent slots, import collision, malformed JSON, cup-save exclusion');
 console.log(`PASS: ${checks} checks; ${playerIds.size} players; 32 Italian + 32 foreign + 61 national editions; 100 completed tournaments.`);
})().catch(e=>{console.error(e);process.exitCode=1});
